mysql:
  image: mysql
  ports:
    - '3306:3306'
  environment:
    - MYSQL_USER=${{values.dbUsername}}
    - MYSQL_PASSWORD=${{values.dbPassword}}
    - MYSQL_DATABASE=${{values.dbHost}}
    - MYSQL_ROOT_PASSWORD=${{values.dbPassword}}
  volumes:
    - './conf.d:/etc/mysql/conf.d:ro'
