apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-service
  name: mysql-service
  namespace: alien-07
spec:
  externalName: mysql-test.ccdeexqykzxr.eu-central-1.rds.amazonaws.com
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: mysql-service
  type: ExternalName
status:
  loadBalancer: {}
