apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: demoapp-db
  labels:
    backstage.io/kubernetes-id: demoapp
spec:
  forProvider:
    region: eu-central-1
    allocatedStorage: 10
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: db.t3.small
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mariadb
    engineVersion: '10.4.13'
    licenseModel: mariadbql-license
    masterUsername: amministratore
    multiAZ: false
    skipFinalSnapshotBeforeDeletion: true
    port: 3306
    publiclyAccessible: true
    storageEncrypted: false
    storageType: standard
  writeConnectionSecretToRef:
    name: rdsmariadbql-conn
    namespace: crossplane-system
  providerConfigRef:
    name: aws-stack-template-provider
