apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: ${{values.rdsRef}}
  labels:
    backstage.io/kubernetes-id: ${{values.component_id}}
spec:
  forProvider:
    region: ${{values.rdsRegion}}
    allocatedStorage: ${{values.rdsDataDiskSizeGb}}
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-2019
    copyTagsToSnapshot: false
    dbInstanceClass: ${{values.rdsInstanceClass}}
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    enablePerformanceInsights: false
    engine: mariadb
    engineVersion: ${{values.rdsEngineVersion | dump}}
    licenseModel: mariadbql-license
    masterUsername: amministratore
    multiAZ: false
    skipFinalSnapshotBeforeDeletion: true
    port: 3306
    publiclyAccessible: true
    storageEncrypted: false
    storageType: ${{values.rdsStorageType}}
  writeConnectionSecretToRef:
    name: rdsmariadbql-conn
    namespace: crossplane-system
  providerConfigRef:
    name: aws-stack-template-provider
