version: '2'

services:
  myapp:
    image: 'idallaserra/spring-java-app'
    environment:
      - 'SPRING_APPLICATION_JSON={"spring": {"datasource":{"url": "jdbc:mysql://35.198.149.129:3306/db_example?useSSL=false", "username": "root", "password": "Zu1r9EiutUQz0KNOCx3oCZ8ZVQK"}}}'
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
     - '8080:8080'


