name: Publish Maven Package and Docker Image
on:
  push:
    branches:
      - "main"
jobs:
  docker-build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      version: ${{ steps.actions_project_version_check.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: avides/actions-project-version-check@v1.2.0
        id: actions_project_version_check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          file-to-check: pom.xml
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.event.repository.owner.name }}/${{ github.event.repository.name }}:${{ steps.actions_project_version_check.outputs.version }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  tag-repo:
    name: Create Tag and Branch
    runs-on: ubuntu-latest
    needs: [docker-build]
    steps:
      - name: Create Branch
        uses: peterjgrainger/action-create-branch@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: "gh-pages"
      - name: Create Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.docker-build.outputs.version }}
