annotations:
  category: ApplicationServer
apiVersion: v2

appVersion: 0.1.0
version: 0.1.0

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
  - name: mariadb
    version: 9.4.2
    repository: https://charts.bitnami.com/bitnami
    condition: mariadb.enabled
    tags:
      - spring-java-app-database
description: Chart for Apache Tomcat
home: https://github.com/bitnami/charts/tree/master/bitnami/tomcat
icon: https://bitnami.com/assets/stacks/tomcat/img/tomcat-stack-220x234.png
keywords:
  - tomcat
  - java
  - http
  - web
  - application server
  - jsp
maintainers:
  - email: containers@bitnami.com
    name: Bitnami
name: tomcat
sources:
  - https://github.com/bitnami/bitnami-docker-tomcat
  - http://tomcat.apache.org
